emphotodev/emphotodev/urls.py
from django.conf import settings
from django.conf.urls import include, url, patterns
from django.conf.urls.static import static
from django.contrib import admin
from apps.companies.views import HomeDetailView, CategoryDetailView, CategoryDetailSliderView, AboutDetailView, \
    AlbumDetailView, ContactView

urlpatterns = patterns('',

                       # other url patterns
                       url(r'^admin', admin.site.urls),
                       url(r'^$', HomeDetailView.as_view(), name="home"),
                       url(r'^about-me/$', AboutDetailView.as_view(), name="about_me"),
                       url(r'^contact/$', ContactView.as_view(), name="contact"),
                       url(r'^categorie/(?P<label>[\w-]+)', CategoryDetailView.as_view(), name="category_detail"),
                       url(r'^album/(?P<pk>[0-9]+)/$', AlbumDetailView.as_view(), name="album_detail"),
                       url(r'^categoriefull/(?P<label>[\w-]+)', CategoryDetailSliderView.as_view(),
                           name="category_detail_full"),
                       # autocomplete urls

                       # comments
                       )

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

### DJANGO REST FRAMEWORK ###

from rest_framework import routers

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = urlpatterns + [
    url(r'^', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

emphotodev/apps/companies/models.py
from django.db import models
from image_cropping import ImageCropField, ImageRatioField
from django.utils.html import mark_safe


class Photo(models.Model):
    image = ImageCropField(blank=True, upload_to='photos')
    cropping = ImageRatioField('image', '2560x1550', size_warning=True)
    slide = models.BooleanField(default=False)
    text = models.CharField(max_length=20, blank=True)
    caption = models.CharField(max_length=50, blank=True)

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="150px" />' % (self.image))

    image_tag.short_description = 'Image'

    def __str__(self):
        return str(self.pk)


class Category(models.Model):
    cover = models.FileField(upload_to="categories")
    label = models.CharField(max_length=30)
    description = models.TextField(max_length=1000, blank=True, null=True)
    info = models.TextField(max_length=1000, blank=True, null=True)
    photos = models.ManyToManyField(Photo, blank=True)
    cit = models.CharField(max_length=256, blank=True)
    order = models.IntegerField(default=0, blank=True)
    home_page = models.BooleanField(default=False)
    video = models.CharField(max_length=1000, blank=True, null=True)

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="150px" />' % (self.cover))

    image_tag.short_description = 'Cover'

    def __str__(self):
        return str(self.label)


class Album(models.Model):
    title = models.CharField(max_length=256, blank=True,help_text="Es. Mario & Gina")
    description = models.TextField(max_length=1000, blank=True, null=True)
    category = models.ForeignKey(Category, blank=True, null=True)
    cover = models.FileField(upload_to="albums",help_text="Immagine di copertina",blank=True)
    photos = models.ManyToManyField(Photo)

    def image_tag(self):
        return mark_safe('<img src="/media/%s" width="100px" />' % (self.cover))

    image_tag.short_description = 'Cover'

    def __str__(self):
        return str(self.description)

emphotodev/apps/companies/forms.py
from django import forms


class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=100,required=False)
    last_name = forms.CharField(max_length=100,required=False)
    telephone = forms.CharField(max_length=100,required=False)
    message = forms.CharField(widget=forms.Textarea,required=False)
    email = forms.EmailField(required=False)

emphotodev/apps/companies/views.py
from django.views import generic
from .models import Category, Photo, Album
from django.db.models import Q
from .forms import ContactForm
from django.views.generic.edit import FormView
from django.core.mail import send_mail
from django.core.mail import EmailMessage



class CategoryDetailView(generic.DetailView):
    model = Category
    template_name = "category.html"

    def get_object(self, queryset=None):
        return Category.objects.get(label__icontains=self.kwargs['label'])

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailView, self).get_context_data(**kwargs)
        context['menu'] = Category.objects.filter(home_page=False).order_by('order')
        context['slides'] = Photo.objects.filter(category=self.get_object(), slide=True)
        context['albums'] = Album.objects.filter(category=self.get_object())
        return context


class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = "album.html"

    def get_context_data(self, **kwargs):
        context = super(AlbumDetailView, self).get_context_data(**kwargs)
        context['menu'] = Category.objects.filter(home_page=False).order_by('order')
        context['albums'] = Album.objects.filter(category=self.get_object().category).filter(
            ~Q(pk=self.get_object().pk))

        return context


class ContactView(FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        """
        Handles POST requests, instantiating a form instance with the passed
        POST variables and then checked for validity.
        """
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def send_mail(self, form):
        subject = "Richiesta informazioni"
        message = form.cleaned_data["message"]
        sender = form.cleaned_data["email"]
        recipients = ['caspani87@gmail.com']

        message = message + " " + sender

        email = EmailMessage(subject, message, to=recipients)
        email.send()

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        self.send_mail(form)
        return super(ContactView, self).form_valid(form)


class CategoryDetailSliderView(generic.DetailView):
    model = Category
    template_name = "category-slider.html"

    def get_object(self, queryset=None):
        return Category.objects.get(label__icontains=self.kwargs['label'])

    def get_context_data(self, **kwargs):
        context = super(CategoryDetailSliderView, self).get_context_data(**kwargs)
        context['menu'] = Category.objects.filter(home_page=False).order_by('order')
        context['slides'] = Photo.objects.filter(category=self.get_object(), slide=True)
        return context


class HomeDetailView(CategoryDetailView):
    model = Category
    template_name = "home.html"

    def get_object(self, queryset=None):
        return Category.objects.get(label__icontains="home")

    def get_context_data(self, **kwargs):
        context = super(HomeDetailView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.filter(home_page=False).order_by('order')
        return context


class AboutDetailView(CategoryDetailView):
    model = Category
    template_name = "about.html"

    def get_object(self, queryset=None):
        return Category.objects.get(label__icontains="home")

    def get_context_data(self, **kwargs):
        context = super(AboutDetailView, self).get_context_data(**kwargs)
        context['categories'] = Category.objects.filter(home_page=False).order_by('order')
        return context

emphotodev/templates/about.html
{% extends "base.html" %}
{% load staticfiles %}

{% block meta %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta name="google-site-verification" content="K96qdFZhiN6hWl1hx4JsfAkT2yKWXtfJIV5pClyQovo"/>
    <meta property="og:url" content="http://www.enricomarcolungo.it/about-me/"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="Enrico Marcolungo Photographer"/>
    <meta property="og:description" content="About me"/>
    <meta property="og:image" content="{% static "images/logo.png" %}"/>
    <title>Enrico Marcolungo @ About Me </title>
{% endblock meta %}

{% block container %}


    <!-- photo of categories -->

    <div class="row black">
        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img class="image-test"
                         src="{% static "images/jube1.jpg" %}">
                </div>
            </div>
        </div>

        <div class="col s12 m4">
            <!--  cit -->

            <div class="row">

                <div class="row">
                    <h5>Chi sono</h5>

                    <p>
                        orem Ipsum is simply dummy text of the printing and typesetting industry. <br> Lorem Ipsum has
                        been
                        the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley
                        of type and scrambled it to make a type specimen book.<br> It has survived not only five
                        centuries,
                        but also the leap into electronic typesetting, remaining essentially unchanged. <br><br>It was
                        popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
                        and more recently with desktop publishing software like Aldus PageMaker including versions of
                        Lorem Ipsum.
                    </p>


                </div>

            </div>
        </div>

        <div class="col s12 m4">
            <div class="card">
                <div class="card-image">
                    <img class="image-test"
                         src="{% static "images/background2.jpg" %}">
                </div>
            </div>
        </div>


    </div>


{% endblock container %}

{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
        });
    </script>

{% endblock %}

emphotodev/templates/album.html
{% extends "base.html" %}
{% load staticfiles %}

{% block meta %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta name="google-site-verification" content="K96qdFZhiN6hWl1hx4JsfAkT2yKWXtfJIV5pClyQovo"/>
    <meta property="og:url" content="http://www.enricomarcolungo.it/album/{{ object.pk }}/"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="Enrico Marcolungo Photographer"/>
    <meta property="og:description" content="{{ object.title }} photos"/>
    <meta property="og:image" content="{% static "images/logo.png" %}"/>
    <title>Enrico Marcolungo @ {{ object.category }} - {{ object.title }}</title>
{% endblock meta %}

{% block container %}


    <!-- photo of categories -->
    <div class="row black">
        <div class="col s12 m3">

            <h5 class="center-align">{{ object.title }}</h5>
            <p class="center-align">
                {% if object.description %}
                    {{ object.description|safe }}
                {% endif %}
            </p>

            <div class="row">
                <div class="col s1"></div>
                <div class="col s11">
                    <div class="fb-like" data-href="http://www.enricomarcolungo.it" data-layout="standard"
                         data-action="like"
                         data-size="small" data-show-faces="true" data-share="true"></div>
                </div>
            </div>

            <div class="row">
                <div class="col s12">
                    <h5 class="center-align">Altri album ({{ object.category.label }})</h5>

                     {% for album in albums %}
                        <div class="card" style="width: 50px;float: left">
                            <div class="card-image">
                                <a href="{% url "album_detail" album.pk %}">
                                <img class="image-test"
                                     src="{{ MEDIA_URL }}{{ album.cover }}">
                                    </a>
                            </div>
                        </div>
                    {% endfor %}


                </div>

            </div>

        <!--
        Video
            <div class="row">
                <div class="col s12">
                    <h5 class="center-align">Backstage</h5>

                    <p class="center-align">
                        {{ category.video|safe }}
                    </p>


                </div>

            </div>
-->

        </div>

        <div class="col s12 m7">
            {% for photo in object.photos.all %}
                <div class="card">
                    <div class="card-image">
                        <img class="image-test"
                             src="{{ MEDIA_URL }}{{ photo.image }}">

                        <script type="text/javascript">
                            var urlImg = "http://www.enricomarcolungo.it{{ MEDIA_URL }}{{ photo.image }}";
                        </script>

                    </div>

                </div>
                <a href="#" onclick="publishOnFB()" style="position: absolute;margin-top: -40px;margin-left: 5px;"><i
                        class="material-icons white-text" title="Pubblica su Facebook">thumb_up</i></a>
            {% endfor %}
        </div>

        <div class="col s12 m2">
            <!--  cit -->

            <div class="row">

                <form class="col s12" action="{% url "contact" %}" method="post">

                    {% csrf_token %}
                    <div class="row">
                        <h5>Richiedi informazioni</h5>

                        <p>
                            {{ object.category.info|safe }}
                        </p>
                        <div class="input-field">
                            <input id="id_first_name" name="first_name" type="text" class="validate">
                            <label for="id_first_name">Nome</label>
                        </div>
                        <div class="input-field">
                            <input id="id_last_name" name="last_name" type="text" class="validate">
                            <label for="id_last_name">Cognome</label>
                        </div>
                        <div class="input-field">
                            <input id="id_telephone" type="tel" class="validate" name="telephone">
                            <label for="id_telephone">Telefono</label>
                        </div>
                        <div class="input-field">
                            <input id="id_email" type="email" class="validate" name="email">
                            <label for="id_email" data-error="wrong" data-success="right">Email</label>
                        </div>
                        <div class="input-field">
                            <textarea id="id_message" class="materialize-textarea" name="message"></textarea>
                            <label for="id_message">Messaggio</label>
                        </div>

                        <div class="col s12">

                            <p class="white-text">
                                <input type="checkbox" id="accept_privacy"/>
                                <label for="accept_privacy" class="white-text"
                                       style="font-size: 12px;overflow: scroll;height: auto;">
                                    Autorizzo il trattamento dei miei dati personali, ai sensi del D.lgs.196 del 30
                                    giugno 2003 (visualizza <a target="_blank"
                                                               href="http://www.iubenda.com/privacy-policy/7988959">l'informativa
                                    completa</a>).
                                </label>

                            </p>

                        </div>

                        <button class="btn waves-effect waves-light right" type="submit" name="action" id="send-contact"
                                disabled>Invia
                            <i class="material-icons right">send</i>
                        </button>

                    </div>

                </form>

            </div>
        </div>
    </div>


    {% include "components/cit.html" with cit=object.cit %}

{% endblock container %}

{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
        function publishOnFB() {


            console.log(urlImg);

            FB.login(function () {
                // Note: The call will only work if you accept the permission request
                FB.api('/me/photos', 'post', {
                    "url": urlImg,
                    "privacy": {
                        "value": 'SELF'
                    }
                }, function (response) {
                    console.log(response);
                    if (response && !response.error) {
                    }
                });
            }, {scope: 'publish_actions'});


        }

        $(document).ready(function () {

            $("#accept_privacy").change(function () {
                if ($(this)[0].checked == true) {
                    $('#send-contact').removeAttr('disabled');
                } else {
                    $('#send-contact').attr('disabled', 'disabled');
                }
            })

        });
    </script>

{% endblock %}

emphotodev/templates/category-slider.html
{% extends "base.html" %}
{% load staticfiles %}

{% block container %}
    <div class="slider fullscreen">
        <ul class="slides">
            {% for photo in object.photos.all %}
                <li>
                    <img src="{{ MEDIA_URL }}{{ photo.image }}"> <!-- random image -->
                    <div class="caption center-align">
                        <h3>{{ photo.text }}</h3>
                        <h5 class="light grey-text text-lighten-3">{{ photo.caption }}</h5>
                    </div>
                </li>
            {% endfor %}
        </ul>

    </div>

{% endblock %}

{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
        $(document).ready(function () {
            $('.slider').slider({full_width: true});
            $("nav").hide();


        });
    </script>
{% endblock %}

emphotodev/templates/category.html
{% extends "base.html" %}
{% load staticfiles %}

{% block meta %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta name="google-site-verification" content="K96qdFZhiN6hWl1hx4JsfAkT2yKWXtfJIV5pClyQovo"/>
    <meta property="og:url" content="http://www.enricomarcolungo.it/{{ category }}"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="Enrico Marcolungo Photographer"/>
    <meta property="og:description" content="{{ category }} photos"/>
    <meta property="og:image" content="{% static "images/jubelog.png" %}"/>
    <title>Enrico Marcolungo @ {{ category }} </title>
{% endblock meta %}

{% block container %}


    <!-- photo of categories -->
    <div class="row black">
        <div class="col s12 m3">

            <h5 class="center-align">{{ category }}</h5>
            <p class="center-align">

                {% if category.description %}
                    {{ category.description|safe }}
                {% endif %}
            </p>

            <div class="row">
                <div class="col s1"></div>
                <div class="col s11">
                    <div class="fb-like" data-href="http://www.enricomarcolungo.it" data-layout="standard"
                         data-action="like"
                         data-size="small" data-show-faces="true" data-share="true"></div>
                </div>
            </div>

            <div class="row">
                <div class="col s12">
                    <h5 class="center-align">Album recenti</h5>

                    {% for album in albums %}
                        <div class="card" style="width: 50px;float: left">
                            <div class="card-image">
                                <a href="{% url "album_detail" album.pk %}">
                                <img class="image-test"
                                     src="{{ MEDIA_URL }}{{ album.cover }}">
                                    </a>
                            </div>
                        </div>
                    {% endfor %}


                </div>

            </div>

            <div class="row">
                <div class="col s12">
                    <h5 class="center-align">Backstage</h5>

                    <p class="center-align">
                        {{ category.video|safe }}
                    </p>


                </div>

            </div>


        </div>

        <div class="col s12 m7">
            {% for photo in object.photos.all %}
                <div class="card">
                    <div class="card-image">
                        <img class="image-test"
                             src="{{ MEDIA_URL }}{{ photo.image }}">

                        <script type="text/javascript">
                            var urlImg = "http://www.enricomarcolungo.it{{ MEDIA_URL }}{{ photo.image }}";
                        </script>

                    </div>

                </div>
                <a href="#" onclick="publishOnFB()" style="position: absolute;margin-top: -40px;margin-left: 5px;"><i
                        class="material-icons white-text" title="Pubblica su Facebook">thumb_up</i></a>
            {% endfor %}
        </div>

        <div class="col s12 m2">
            <!--  cit -->

            <div class="row">

                <form class="col s12" action="{% url "contact" %}" method="post">

                    {% csrf_token %}
                    <div class="row">
                        <h5>Richiedi informazioni</h5>

                        <p>
                            {{ category.info|safe }}
                        </p>
                        <div class="input-field">
                            <input id="id_first_name" name="first_name" type="text" class="validate">
                            <label for="id_first_name">Nome</label>
                        </div>
                        <div class="input-field">
                            <input id="id_last_name" name="last_name" type="text" class="validate">
                            <label for="id_last_name">Cognome</label>
                        </div>
                        <div class="input-field">
                            <input id="id_telephone" type="tel" class="validate" name="telephone">
                            <label for="id_telephone">Telefono</label>
                        </div>
                        <div class="input-field">
                            <input id="id_email" type="email" class="validate" name="email">
                            <label for="id_email" data-error="wrong" data-success="right">Email</label>
                        </div>
                        <div class="input-field">
                            <textarea id="id_message" class="materialize-textarea" name="message"></textarea>
                            <label for="id_message">Messaggio</label>
                        </div>

                        <div class="col s12">

                            <p class="white-text">
                                <input type="checkbox" id="accept_privacy"/>
                                <label for="accept_privacy" class="white-text"
                                       style="font-size: 12px;overflow: scroll;height: auto;">
                                    Autorizzo il trattamento dei miei dati personali, ai sensi del D.lgs.196 del 30
                                    giugno 2003 (visualizza <a target="_blank"
                                                               href="http://www.iubenda.com/privacy-policy/7988959">l'informativa
                                    completa</a>).
                                </label>

                            </p>

                        </div>

                        <button class="btn waves-effect waves-light right" type="submit" name="action" id="send-contact"
                                disabled>Invia
                            <i class="material-icons right">send</i>
                        </button>

                    </div>

                </form>
            </div>
        </div>
    </div>


    {% include "components/cit.html" with cit=object.cit %}

{% endblock container %}

{% block javascripts %}
    {{ block.super }}
    <script type="text/javascript">
        function publishOnFB() {

            FB.login(function () {
                // Note: The call will only work if you accept the permission request
                FB.api('/me/photos', 'post', {
                    "url": urlImg,
                    "privacy": {
                        "value": 'SELF'
                    }
                }, function (response) {
                    console.log(response);
                    if (response && !response.error) {
                    }
                });
            }, {scope: 'publish_actions'});


        }


        $(document).ready(function () {

            $("#accept_privacy").change(function () {
                if ($(this)[0].checked == true) {
                    $('#send-contact').removeAttr('disabled');
                } else {
                    $('#send-contact').attr('disabled', 'disabled');
                }
            })

        });

    </script>

{% endblock %}

emphotodev/templates/components/cit.html
{% load staticfiles %}
<div class="row">
    <div>
        <h6 class="center-align">{{ cit }}(Cit.)</h6>
    </div>
    <div class="center-align">
        <img width="20%" class="image-test"
             src="{% static "images/background2.jpg" %}">
    </div>
</div>

emphotodev/templates/components/menu_top.html
{% load static %}
<!-- {{ categories }} -->
<!-- {{ logo }} -->

<div class="navbar-fixed">
    <nav class="black">
        <ul id="slide-out" class="side-nav">
            <li>
                <img style="padding-left: 20px;padding-top: 10px" src="{% static "images/butterfly.png" %}">
            </li>
            <li><a href="/">Home</a></li>
            <li><a href="/about-me/">Chi sono</a></li>

            {% for link in menu %}
                <li><a href="{% url "category_detail" label=link.label %}">{{ link.label }}</a></li>
            {% endfor %}

        </ul>

        <div class="row">
            <div class="col s3">
                <a href="#" data-activates="slide-out" class="button-collapse show-on-large large-menu"><i
                        class="material-icons white-text">menu</i></a>

            </div>
            <div class="col s6">
                <div class="logo-wrapper"><a href="/"><img class="logo__img"
                                                           src="{% static "images/logo.png" %}"></a></div>
            </div>

            <div class="col s3">
                <a
                        href="https://www.instagram.com/enrico_marcolungo/"> <img
                        class="logo__instagram"
                        src="{% static "images/instagram-icon.png" %}"></a>
                <a
                        href="https://www.facebook.com/enrico.marcolungo.5"> <img
                        class="logo__fb" src="{% static "images/facebook.png" %}"></a>

            </div>


        </div>
    </nav>
</div>

emphotodev/templates/components/slider.html
{% load static %}
{% load cropping %}
<img src="">

<div class="row sliderhome">
    <div class="col s12 slider">
        <ul class="slides">
            {% for photo in slides %}
                <li>
                    <img src="{% cropped_thumbnail photo "cropping" scale=1.0 %}"> <!-- random image -->
                    <div class="caption center-align">
                        <h3>{{ photo.text }}</h3>
                        <h5 class="light grey-text text-lighten-3">{{ photo.caption }}</h5>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </div>
</div>

emphotodev/templates/home.html
{% extends "base.html" %}
{% load staticfiles %}

{% block meta %}
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no"/>
    <meta name="google-site-verification" content="K96qdFZhiN6hWl1hx4JsfAkT2yKWXtfJIV5pClyQovo"/>
    <meta property="og:url" content="http://www.enricomarcolungo.it"/>
    <meta property="og:type" content="website"/>
    <meta property="og:title" content="Enrico Marcolungo Photographer"/>
    <meta property="og:description" content="Home"/>
    <meta property="og:image" content="{% static "images/logo.png" %}"/>
    <title>Enrico Marcolungo - Photographer </title>
{% endblock meta %}

{% block container %}

    <!-- photo of categories -->
    <div class="row grid black">
        <div class="grid-sizer"></div>

        {% for category in categories %}
            <div class="grid-item">
                <a href="{% url "category_detail" label=category.label|lower %}"><img
                        src="{{ MEDIA_URL }}{{ category.cover }}"></a>
                <span class="masonry-image-caption">{{ category.label }}</span>
            </div>
        {% endfor %}

    </div>

    <!--  cit -->
    {% include "components/cit.html" with cit=object.cit %}
{% endblock container %}



{% block javascripts %}
    {{ block.super }}

    <script type="text/javascript">

    </script>
{% endblock %}

emphotodev/templates/login.html
{% load staticfiles %}